// <auto-generated />
namespace QverbITMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class IncidentColumns : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncidentColumns));
        
        string IMigrationMetadata.Id
        {
            get { return "201412111017095_IncidentColumns"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
