// <auto-generated />
namespace QverbITMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Projects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Projects));
        
        string IMigrationMetadata.Id
        {
            get { return "201412111221355_Projects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
